name: Backend CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL}}
      DB_URL_TEST: ${{ secrets.DB_URL_TEST }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASS: ${{ secrets.REDIS_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 23.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 23.9.0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
