name: Backend CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 23.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 23.9.0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
